# Wisdom

In this video, we provide a concise overview of the initial unit’s four key themes: knowledge, humility, friendship, and rhetoric. While the first topic examines some fundamental concepts regarding the essence of wisdom, the majority of this unit is dedicated to unveiling practical skills essential for leading a wise and fulfilling life. We explore how to cultivate and apply these skills, emphasizing a proactive approach to embodying the principles of wisdom in our daily experiences.

**Wisdom Unit 1 Introduction** Video (6 min 10 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/863371291?h=be205cbd14&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 1, Introduction"></iframe>

</div>

## Overview {-}

### Topics {-}

This unit is divided into the following four topics:

1. Wisdom and Knowledge
2. Wisdom and Humility
3. Wisdom and Friendship
4. Wisdom and Rhetoric

### Learning Outcomes {-}

When you’ve completed this unit, you will have learned how to:

- Identify and understand the role wisdom plays in knowledge, humiloity, friendship and rhetoric
- Practice and apply the skills of wisdom to knowledge, humility, friendship and rhetoric
- Apply these skills to the types of actions a wise person may take
- Enhance your skills of wisdom and reason to live life within the context of justice and faith
- Develop the skills to become a well-rounded person and citizen and live a wise and just life  

## 1.1 Wisdom and Knowledge {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Read Topic Reading
4. Complete Note-Taking Exercise
5. Complete Topic Questionnaire
6. Watch Optional Video

### Topic Notes {-}

In this topic, we delve into the essence of wisdom and its intricate relationship with knowledge. Wisdom transcends mere information; it is a practical virtue essential for navigating life’s complexities, confronting challenges, and ideally, circumventing adversity. While wisdom is rooted in practicality, it necessitates a foundation of knowledge. To lead a well-lived life, wisdom calls for an understanding of the right beliefs and the skill to apply them judiciously and timely.

Philosopher Robert Nozick contends that a wise individual possesses beliefs spanning various facets of life, encompassing crucial values, strategies for goal achievement, and the requisite steps to realize these objectives. Furthermore, wise actions, integral to a fulfilling life, stem from the application of these foundational beliefs. Mere possession of knowledge does not equate to wisdom; the discerning application of beliefs in one’s behavior is paramount.

Nozick acknowledges that, despite meticulous planning and application of appropriate beliefs and actions, unforeseen challenges may arise, disrupting our endeavors. A wise individual anticipates this inherent uncertainty, preparing for potential setbacks, acquiring the skills to avert failure, and developing resilience to respond effectively when faced with adversity. In essence, wisdom involves not only knowing what is right but also navigating the unpredictable nature of life with foresight, adaptability, and a resilient spirit.

### Topic Video {-}

In this video, you will learn about wisdom and knowledge from Robert Nozick’s piece, “*What is Wisdom and Why do Philosophers Love it So?*”

**Wisdom and Knowledge Unit 1 Topic 1** Video (11 min 15 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/863371336?h=1432d24ea4&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 1, Topic 1, Knowledge"></iframe>

</div>

### Topic Reading {-}

- Robert Nozick - [*What is Wisdom and Why Do Philosophers Love It So?*](assets/u1/PHIL-100-Nozick-What-is-Wisdom.pdf){target="_blank"}

### Note-Taking Exercise {-}

**These note-taking exercises are designed to help you navigate challenging texts. While reading through the entire text without interruption can provide a grasp of the author’s overarching message, it might be overwhelming in some cases, making comprehension difficult. In such instances, students may be tempted to abandon the text and seek online summaries, which may not accurately reflect the author’s intent.**

**If you find the readings challenging, one effective strategy is to break down the text, either by section or even paragraph. Take point-form notes on the key ideas within each chunk of the text. As you progress and continue taking notes, you may find it helpful to revisit earlier sections to revise or add additional insights.**

**By the end of this exercise, you should have detailed notes covering the entire text, enhancing your understanding of the author’s intended message. This approach proves particularly beneficial in courses where content recall is crucial for exams or when crafting a research essay, helping you better recall various research points you’ve gathered.**

```{block2, type='reflect'}

Click the Download button on the left after you've completed all the notes for this reading and save the answers to your computer as you will be required to submit your downloaded notes to this reading as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=581" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Topic Questionnaire {-}

```{block2, type='reflect'}

- Answering these questions will help you reflect on the topic content and prepare you for your Unit 1 Reflection Assignment.
- Click the Download button on the left after you've completed all the questions for this unit and save the answers to your computer as you will be required to submit the downloaded answers to these questions as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=570" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 5 minute 55 second optional video, philosophers Valerie Tiberius and Philip Kitcher, as well as psychologist Lisa Feldman Barret discuss their definitions of wisdom.

[Watch: *What is Wisdom?*](https://youtu.be/obqedyeUcwk){target="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/obqedyeUcwk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

## 1.2 Wisdom and Humility {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Read Topic Reading
4. Complete Note-Taking Exercise
5. Complete Topic Questionnaire
6. Watch Optional Video

### Topic Notes {-}

Within this topic, our attention shifts to the intertwining realms of wisdom and humility. A wise individual possesses a keen awareness of the boundaries of their knowledge, acknowledging both what they comprehend and what lies beyond their understanding. Here, “ignorance” is not disparaging but denotes a specific lack of knowledge in a given domain.

The dialogue unfolds in Plato’s “the Apology,” where Socrates, perplexed by the Oracle of Delphi’s proclamation that no one is wiser than he, embarks on a quest to unravel the meaning of this paradox. Through dialogues with politicians, poets, and artisans, Socrates discovers that those who claim profound knowledge often lack true understanding. The pivotal distinction lies in Socrates’ awareness of his ignorance, particularly regarding the nature of beauty and what is good, in contrast to others who falsely believe they possess knowledge. This self-awareness becomes the hallmark of Socrates’ wisdom.

Applying the principle of acknowledging ignorance to the pursuit of wisdom involves cultivating a humble stance towards life’s intricate questions. Whether grappling with the interpretation of the Bible, contemplating evolutionary theories, exploring the nature of sexuality, evaluating the impact of social media, or assessing the effectiveness of political leadership, a wise person approaches these complex issues with humility. This involves posing thoughtful questions, recognizing the limits of one’s own understanding, refraining from hasty judgments, and maintaining a receptivity to evolving perspectives. In essence, humility becomes a guiding virtue in the pursuit of wisdom, fostering a mindset that values curiosity, open-mindedness, and the continual quest for understanding.

### Topic Video {-}

In this video, you will learn about wisdom and humility from Plato’s *Apology*.

**Wisdom and Humility Unit 1 Topic 2** Video (13 min 54 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/863371368?h=2355f01fe6&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 1, Topic 2, Humility"></iframe>

</div>

### Topic Reading {-}

- Plato - *Apology* - https://classics.mit.edu/Plato/apology.html

### Note-Taking Exercise {-}

```{block2, type='reflect'}

Click the Download button on the left after you've completed all the notes for this reading and save the answers to your computer as you will be required to submit your downloaded notes to this reading as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=582" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Topic Questionnaire {-}

```{block2, type='reflect'}

- Answering these questions will help you reflect on the topic content and prepare you for your Unit 1 Reflection Assignment.
- Click the Download button on the left after you've completed all the questions for this unit and save the answers to your computer as you will be required to submit the downloaded answers to these questions as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=571" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 2 minute 59 second optional video with Dr. Ian Church, *What is Intellectual Humility*? A doxastic account. Here is the first of three parts. If you have the time, you should watch all three parts.

[Watch: *What is Intellectual Humility?*](https://www.youtube.com/watch?v=8CZIkGEJYRY){target="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/8CZIkGEJYRY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

## 1.3 Wisdom and Friendship {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Read Topic Reading
4. Complete Note-Taking Exercise
5. Complete Topic Questionnaire
6. Watch Optional Video

### Topic Notes {-}

The third topic explores the intricate relationship between wisdom and friendship, emphasizing the discerning approach a wise individual takes in understanding the various dimensions of companionship. To navigate this terrain effectively, it is imperative to comprehend the diverse types of friendships, as expounded by Aristotle.

Aristotle categorizes friendships into three distinct types: those based on utility, pleasure, and virtue. Friends of utility serve as instrumental connections, such as business partners or teammates in sports. Friends of pleasure share enjoyable activities, while friends of virtue embody individuals with admirable qualities, actively contributing to our moral development. Aristotle contends that friendships rooted in virtue are the most profound, albeit challenging to cultivate. Such friendships extend beyond mere utility or pleasure; they transcend difficulties, demonstrating a genuine concern for one another’s character development.

Thomas Aquinas further enriches this discourse by cautioning against qualities that undermine the pursuit of virtue in friendships. Envy, manifesting as displeasure at a friend’s success, and arrogant pride, reflected in an inability to handle jests or an inflated sense of self-worth, are identified as detrimental vices. Aquinas urges us to be vigilant in recognizing and avoiding these pitfalls, both in our friends and within ourselves.

Crucially, this exploration prompts introspection. Are our friendships solely utilitarian or pleasure-seeking? Do we harbor envy towards our friends’ accomplishments? Do we exhibit arrogant pride? The video introduces these insights from Aristotle and Aquinas, providing valuable guidance to nurture robust and virtuous friendships conducive to a life well-lived.

### Topic Video {-}

In this video, you will learn about wisdom and friendship from Aristotle’s *Nicomachean Ethics*, Books 8, 9 and 10, and some additional points from Thomas Aquinas.

**Wisdom and Friendship Unit 1 Topic 3** Video (24 min 18 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/863371397?badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 1, Topic 3, Friendship"></iframe>

</div>

### Topic Reading {-}

- Aristotle - [*Nicomachean Ethics*, Books VIII, IX and X](assets/u1/PHIL-100-Aristotle-NE-VIII-IX-X.pdf){target="_blank"}

### Note-Taking Exercise {-}

```{block2, type='reflect'}

Click the Download button on the left after you've completed all the notes for this reading and save the answers to your computer as you will be required to submit your downloaded notes to this reading as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=583" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Topic Questionnaire {-}

```{block2, type='reflect'}

- Answering these questions will help you reflect on the topic content and prepare you for your Unit 1 Reflection Assignment.
- Click the Download button on the left after you've completed all the questions for this unit and save the answers to your computer as you will be required to submit the downloaded answers to these questions as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=572" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 7 minute 21 second optional video, you will learn further details about Aristotle’s view of friendship.

[Watch: *Aristotle’s Timeless Advice on What Real Friendship Is and Why It Matters*](https://www.youtube.com/watch?v=F18kSA8OxqY){targt="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/F18kSA8OxqY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

## 1.4 Wisdom and Rhetoric {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Read Topic Reading
4. Complete Note-Taking Exercise
5. Complete Topic Questionnaire
6. Watch Optional Video

### Topic Notes {-}

The final topic examines the intersection of wisdom and rhetoric, recognizing that engaging in arguments with others is an inherent aspect of daily life. A wise individual possesses the skill to navigate these discussions without descending into conflict. According to Jay Heinrichs, productive argumentation requires a clear understanding of the desired outcome.

The crucial skill in constructive argumentation involves defining the appropriate goal for the situation. Are you seeking to influence a decision, aiming for a sense of victory, or hoping to shift your opponent’s mood or perspective? Perhaps your goal is to efficiently conclude the argument while maintaining a positive relationship with the other person. Each goal requires a tailored approach, prompting consideration of the feasibility of your objectives and the methods to achieve them.

Moreover, one ought to consider reflecting on the post-argument scenario. Do you wish to uphold the relationship after the disagreement? What compromises are you willing to make, and are you prepared to acknowledge defeat from your opponent’s perspective if it serves your overarching goal? Heinrichs encourages a thoughtful examination of the argument’s purpose, emphasizing the strategic choices and compromises necessary to align with your desired outcome.

In essence, this exploration aims to equip individuals with the skills and insights to engage in persuasive and constructive discussions, fostering an environment where arguments serve as tools for understanding and collaboration rather than sources of conflict.

### Topic Video {-}

In this video, you will learn about wisdom and rhetoric from Jay Heinrich’s *Thank You for Arguing*, Chapter 2 “Set Your Goals”.

**Wisdom and Rhetoric Unit 1 Topic 4** Video (12 min 19 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/863371442?h=66df806e96&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 1, Topic 4, Rhetoric"></iframe>

</div>

### Topic Reading {-}

- Jay Heinrichs - [*Thank You for Arguing*](assets/u1/PHIL-100-Heinrichs-Thank-You-for-Arguing.pdf){target="_blank"}

### Note-Taking Exercise  {-}

```{block2, type='reflect'}

Click the Download button on the left after you've completed all the notes for this reading and save the answers to your computer as you will be required to submit your downloaded notes to this reading as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=584" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Topic Questionnaire {-}

```{block2, type='reflect'}

- Answering these questions will help you reflect on the topic content and prepare you for your Unit 1 Reflection Assignment.
- Click the Download button on the left after you've completed all the questions for this unit and save the answers to your computer as you will be required to submit the downloaded answers to these questions as part of your Unit 1 Reflection Assignment.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=576" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 4 minute 29 second optional video. Here, Camille A. Langston, a specialist in rhetoric and nineteenth-century women, explains the basics of deliberative rhetoric and shares tips for appealing to the ethos, logos, and pathos of your audience.

[Watch: *How to Use Rhetoric to Get What You Want*](https://www.youtube.com/watch?v=3klMM9BkW5o){target="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/3klMM9BkW5o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```