# Reason

This final unit is about arguments. This unit is valuable because everything we’ve discussed so far, both about wisdom and faith, is built upon the foundation of arguments. We give arguments for our views about wisdom. We give arguments about issues of faith and rationality. This last unit provides the opportunity for you to learn a basic skill of how to identify an argument, whether the argument is located in a book, and more often on YouTube, a podcast, and in the news. Note that we do not cover how to evaluate arguments in this unit. Evaluating arguments is a skill taught in other philosophy courses.

In topic 1, we learn about the parts of the argument, such as the proper terms used to designate these different parts. If we wish to learn how to identify arguments, we must know what terms to look for. In topic 2, we learn about how to label and structure arguments. Often people do not organize their argument clearly and so we must learn how to reconstruct the argument so that we know the conclusion and the reasons for supporting the conclusion. In topic 3, we tackle slightly more complicated arguments and learn how to interpret what the author intended to say. As practiced in topic 2, people often organize their arguments (or, occasionally, non-arguments) in a confusing way. Moreover, we will learn about tricky terms often used in arguments, such as the terms “if” and “then”. In the final topic, we practice identifying difficult arguments, which often include long texts, run on sentences, and additional irrelevant content to the argument being put forward. Our task in the final topic is to use our skills practiced in topics 1-3 to identify more difficult arguments.

**Reason Unit 3 Introduction** Video (5 min 41 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/889164879?h=3f2c085f03&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 3, Introduction"></iframe>

</div>

## Overview {-}

### Topics {-}

This unit is divided into the following four topics:

1. Parts and Keywords of an Argument
2. Labelling and Restructuring
3. Interpreting Arguments and Conditionals (If…Then)
4. Identifying and Practicing Difficult Arguments

### Learning Outcomes {-}

When you’ve completed this unit, you will have learned how to:

- Identify the parts of an argument and how to label and structure these parts
- Interpret arguments with ambiguous terminology to be made more precise
- Develop a greater understanding of how arguments work in contemporary culture, including issues of justice and faith
- Practice the skills necessary for navigating arguments in literature, news, and podcasts
- Appreciate the value and skill of knowing how to handle the basic features of an argument

## 3.1 Parts and Keywords of an Argument {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Complete Logic Exercise 1
4. Complete Logic Exercise 2
5. Watch Optional Video

### Topic Notes {-}

In this topic, we learn about the parts of the argument and the words often used to designate these parts. Arguments are made up of statements. Statements are claims that are either true or false. Sometimes statements are whole sentences, while other times statements are phrases. For example, the question, “Is there a God?” is not a statement because the question does not state something that is either true or false. The answer to this question, “yes there is a God,” or “no, there is no God” are statements because they express claims that are either true or false. Other parts of the argument are the premises and conclusion. The premises are the statements that support the conclusion. The conclusion is the statement that is being argued for by the premises. The inference is the move from the premises to the conclusion. Imagine someone says they believe that God exists. This is their conclusion. You ask them, “why think that God exists?” Their response is going to be a reason (i.e. a premise) or a set of reasons (i.e. a set of premises) that are supposed to support their conclusion. The inference is the nature of the support from premise to conclusion.

Some of the primary keywords of an argument are terms that describe premises and conclusions. For example, the word “therefore” often picks out a conclusion. The statement that follows from the term “therefore” may act as a conclusion. Terms that describe premise can be “all” “every” “some”. As we shall see, these types of words help us identify the premises of an argument.

### Topic Video {-}

In this video, you will learn about the parts and keywords of an argument. The parts of an argument include statements and never include non-statements. A statement is a claim that is either true or false. Statements in an argument can be premises and/or conclusions. There are often keywords that designate premises and conclusions, such as “all” and “therefore”, respectively.

**Parts and Keywords of an Argument Unit 3 Topic 1** Video (6 min 46 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/889164919?h=8ccf02be69&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 3, Topic 1, Parts and Keywords"></iframe>

</div>

### Logic Exercise 1 {-}

```{block2, type='reflect'}

In this activity, you will learn about the parts of an argument, including statements and non-statements, premises, and conclusions.

An argument is a set of statements organized in a specific way, for example:

1. All humans are mortal. (Premise)
2. Lucy is human. (Premise)
3. Therefore, Lucy is mortal. (Conclusion)

The statements above are organized as an argument because one of the statements, the conclusion, is supported by the other set of statements, the premises. By reading these premises and the conclusion carefully, one can see that the premises support the truth of the conclusion. **For our purposes, the order of the premises does not matter**. For example, the following argument is the same as the argument above:

1. Lucy is human.
2. All humans are mortal.
3. Therefore, Lucy is mortal.

The space between the premises and the conclusion is called the **inference**. The term “inference” refers to the relationship between premises and conclusion, and that relationship changes depending on the type of argument in use. Put in a different way, the inference refers to how one moves from premise to conclusion. Sometimes that inference is one of certainty, in that the truth of the premises guarantees the truth of the conclusion; other times that inference is one of probability, in that the truth of the premises raises the probable truth of the conclusion. **(You are not required to know about the different types of inferences in this class)**.

The **premises** are the “reasons” for why one should think the **conclusion** is true, and therefore the conclusion is being defended with those premises. The premises and conclusion will always be described with **statements**, and statements are claims that are **either true or false**. Non-statements, however, do not express claims that are either true or false, and thus non-statements are never premises or conclusions. Knowing the difference between statements and non-statements is important because that knowledge will help with identifying the parts of the argument. For example:

1. Apples are red.
2. Tony Stark is Iron Man.
3. Was that a magic trick?
4. Hey, partner!

The first two examples are statements because they express claims that are either true or false. The third example is a question and does not express a claim that is either true or false. Therefore, the third example is a non-statement. (Of course, if one answered the question by saying, “that is a magic trick,” then that answer to the question is a statement that is either true or false). The fourth example is an exclamatory greeting and does not express a claim that is either true or false. Therefore, the fourth example is a non-statement. Remember, then, that arguments are made up of statements and never made up of non-statements.  

Note that a **statement** is different from a **sentence**. A sentence has a subject and a predicate. The subject is what or whom the sentence is about, and the predicate is a description of the subject and contains the verb. Sometimes a whole sentence is one statement, for example:

> “The cat is in the hat.”

That entire sentence is a statement because the sentence is either true or false. Other times a whole sentence includes multiple statements, for example:

> “If the cat is in the hat, then the fish is in the bowl.”

In that example, the first part, “the cat is in the hat,” is the first statement, and the second part, “the fish is in the bowl,” is the second statement. So even though that example is one sentence, the entire sentence includes multiple statements that are either true or false.

More difficult sentences may include both statements and non-statements, for example:

> “Stop, the train is approaching.”

In that example, the first part, “Stop,” is a non-statement, and the second part, “the train is approaching,” is a statement. The reason is because the word “Stop” does not express a claim that is either true or false, and the phrase “the train is approaching” does express a claim that is either true or false. **When identifying the premises and conclusion of an argument, one should only focus on statements and always ignore non-statements.**

### Identifying Statements and Non-statement {-}

**Which of the following are statements? Which of the following are non-statements?. Identify the statements and non-statements by dragging down the appropriate statement and non-statement to the corresponding box below.**

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=411" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Logic Exercise 2 {-}

```{block2, type='reflect'}

In this activity, you will learn about the keywords of an argument, including keywords that designate the premises and the conclusions of an argument.

Some arguments are difficult to locate because the premises and conclusion remain unclear. In those difficult cases, one strategy for identifying the argument is locating **keywords** indicating the premises and conclusion. Keywords that indicate premises include: **“All, every, most, some, none, for, because, If…then.”** Keywords that indicate the conclusion are: **“therefore, so, thus, hence, consequently, it follows that…”** Consider the following example:

  1. **All** humans are mortal. (Premise)
  2.  Lucy is a human. (Premise)
  3.  **Therefore**, Lucy is mortal. (Conclusion)

In that example, the first premise follows the term “All,” and the conclusion follows the term “Therefore.” The second premise does not have a keyword, but, in this case, the reader knows that statement is not the conclusion – because the conclusion was identified already with the keyword “therefore” – and so the second statement must be a premise (this isn’t always the case, but we needn’t be concerned about that here). The argument is easy to identify because both the premise and conclusion have keywords.

### Identifying Premises and Conclusions {-}

**Identify which of the following are premises and which are conclusions by clicking the correct answer.**

**Checklist**

- Focus on statements and ignore non-statements
- Locate the premises and conclusion using keywords

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=413" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 5 minute 24 second optional video, you will learn about the basic structure of an argument.

[Watch: *Critical Thinking #3: Types of Arguments*](https://www.youtube.com/watch?v=wbRxR53F3rI){target="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/wbRxR53F3rI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

## 3.2 Labelling and Restructuring {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Complete Logic Exercise 1
4. Complete Logic Exercise 2
5. Watch Optional Video

### Topic Notes {-}

In the previous topic, we learned about the parts and keywords of an argument. In this topic, we learn how to label these parts of the argument and then restructure the argument vertically, with premises and conclusion, so that we may see the argument clearly. The steps for applying these tools follow this pattern: (i) focus on statements and ignore non-statements. Recall from the previous topic that arguments are made up of statements only and never non-statements. Thus, only focus on statements and cross out any non-statements. (ii) Locate the premises and conclusion amongst the set of statements using keywords. As discussed, premises and conclusions often have terms that designate them, such as “therefore”.

Once the argument has been labelled, the next step is to restructure the argument vertically with the premises on top and the conclusion beneath. This way we can see what the author’s argument is exactly. That is, we can see the conclusion – the main point of their position – and the reasons (i.e. premises) for thinking the conclusion is true. Once these statements are ordered correctly, anyone can see the argument. The reader needn’t labour over the text and the many confusing non-statements to locate the point of the passage.

### Topic Video {-}

In this video, you will learn about labelling and restructuring arguments. Labelling an argument involves inserting the letter (p) next to the premises and the letter (c) next to the conclusion. You then restructure the argument vertically with the premises on top and the conclusion beneath.

**Labelling and Restructuring Unit 3 Topic 2** Video (8 min 56 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/889164959?h=c6d86e2284&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 3, Topic 2, Labelling and Restructuring"></iframe>

</div>

### Logic Exercise 1 {-}

```{block2, type='reflect'}

In this activity, you will learn how to label the parts of the argument by adding the letters (p) and (c) in front of the premise(s) and conclusion(s). For example:

> “All humans are mortal, and Lucy is a human. So, Lucy is mortal.”

Unlike the examples of arguments in the topics 1 and 2, notice that this argument is not written vertically but horizontally. Most arguments written in ordinary discourse (e.g. the news, Facebook, etc.) will be expressed horizontally. That horizontal format already makes the argument more difficult to locate. The first sentence includes two statements and both statements are different premises of the argument. The conclusion is the second sentence indicated by the keyword “So.” The objective is to label the premises and conclusion with symbols so that the reader can identify the argument more accurately. In doing so, begin by first labeling the premises and conclusion by writing the letter “p” in parentheses at the beginning of the premises, and the letter “c” in parentheses next to the conclusion. For example:

> **(P)** All humans are mortal, and **(P)** Lucy is a human. **(C)** So, Lucy is mortal.

In that example, “P” stands for premise and (C) means conclusion. **Note again: the order of the premises does not matter in this Unit. One can reverse the order of the premises and produce the same argument**. When reading more complex arguments, labeling the premises and conclusion becomes essential to be sure one correctly identifies the argument.

### Label the Premises and Conclusions {-}

**Identify which of the following are premises and which are conclusions. Label by filling the blanks using the appropriate letters.**

**Checklist**

- Focus on statements and ignore non-statements
- Locate the premises and conclusion using keywords
- Label the premises and conclusion by inserting the appropriate letter in the blank in front of the statements: P for premise, and C for Conclusion. Be sure to ignore non-statements by inserting an "X" in the blank in front of the non-statement.

**Example**

Argument:
> “All conservatives are Christian. Charlie is conservative. Therefore, Charlie is Christian.”

Solution:
> (P) All conservatives are Christian. (P) Charlie is conservative. (C) Therefore, Charlie is Christian.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=414" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Logic Exercise 2 {-}

```{block2, type='reflect'}

As illustrated in the previous lessons and activities, notice that writing an argument in vertical form, with premises on top and the conclusion on the bottom, is the most effective way to illustrate the final argument. For example:

1. All humans are mortal. (P)
2. Lucy is a human. (P)
3. Therefore, Lucy is mortal. (C)

That vertical format is valuable for the reader to know exactly what the argument is about. Unfortunately, arguments in ordinary discourse are not written in that vertical fashion - as illustrated in Topic 3, where arguments were written horizontally - and therefore one must restructure the horizontal argument format to a vertical argument format. In Topic 4, we practice all of the methods above with the aim of restructuring the argument vertically.

### Label and Structure the Argument {-}

**This activity has two steps. The first step is to click/drag the appropriate letter into the box to label the premises and conclusion. In the second step, click/drag the appropriate premise and conclusion to complete the vertical argument.**

**Checklist**

- Focus on statements and ignore non-statements
- Locate the premises and conclusion using keywords
- Label the premises and conclusion using letters in parentheses
- Restructure the argument vertically, with premises on top and the conclusion on the bottom

For example:

> “Lucy is a teacher. All teachers drink coffee. Therefore, Lucy drinks coffee.”

Step 1: Label the argument

> (P) Lucy is a teacher. (P) All teachers drink coffee. (C) Therefore, Lucy drinks coffee.

Step 2: Restructure the argument vertically

1. Lucy is a teacher. (P)
2. All teachers drink coffee. (P)
3. Therefore, Lucy drinks coffee. (C)

#### Practice Exercises {-}

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=415" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 1 minute 22 second optional video, you will learn about the basic structure of an argument, with brief attention to what makes a bad argument.

[Watch: *Ninety Second Philosophy: Arguments*](https://www.youtube.com/watch?v=Z7f_uuy1JcM){target="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Z7f_uuy1JcM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

## 3.3 Interpreting Arguments and Conditionals (If…Then) {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Complete Logic Exercise 1
4. Complete Logic Exercise 2
5. Watch Optional Video

### Topic Notes {-}

In the first two topics, we learned some foundational skills for identifying arguments, such as the parts and keywords of an argument, and the methods for labeling and restructuring arguments. The challenge, however, is that ordinary discourse – both written and verbal – often makes the argument difficult to identify. We often must interpret what we think the author intended to say about their view and then structure the argument according to this intention. In this topic, we practice the skill of interpretating arguments. One strategy for interpreting an argument is the “Why/Because” strategy. If it’s difficult to identify the premises and conclusion, then look for statements that may follow with a hypothetical “why”. Such statements may be the conclusion(s). The reason is that concluding statements have by definition reasons for them. And the term “why” may pick out these reasons. The term “because” often precedes a reason (i.e. a premise) and so looking for statements that may be preceded with “because” may help with identifying the premises.

A second skill of interpretation is learning to navigate conditional statements. A conditional is a “if … then” statement. For example, “If it’s raining outside, then we can’t go to the park.” Sentences with the words “if” and “then” may be interpreted in different ways depending on the order of these words. In this topic we practice some of these interpretive skills.

### Topic Video {-}

In this video, you will learn some strategies for interpreting arguments. Interpretation is important because we often we fail to clearly communicate the argument. One strategy for interpretation is called the “why/because” strategy. This strategy involves looking for statements that could be followed with a hypothetical “why”, and statements that precede with a hypothetical “because”. In addition, you will learn how to interpret conditional sentences with the term “if” and “then”.

**Interpreting Arguments and Conditionals (If…Then) Unit 3 Topic 3** Video (15 min 32 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/889164999?h=fbfb392482&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 3, Topic 3, Interpretation and Conditionals"></iframe>

</div>

### Logic Exercise 1 {-}

```{block2, type='reflect'}

Another challenge with arguments written in ordinary discourse is not only that they’re written horizontally but they lack keywords for identifying premises and conclusions. When there are no keywords for identifying premise and conclusion, the reader must interpret what the author intended to say and then determine which statements are the premises and conclusion. Consider two examples, the first simpler and the second more complex. The first example is the following:

> “I think Lucy is mortal. She is human and humans are mortal.”

This example does not include a keyword for the conclusion but rather uses the phrase “I think.” Furthermore, note that the conclusion comes first, “I think Lucy is mortal.” That informal way of writing the conclusion makes identification more challenging. Premise (1) also includes the pronoun “she”, which in this case refers to “Lucy.” Note also that premises (1) and (2) are statements within the same sentence, respectively, and lack keywords for identification. In most situations, arguments resemble this example in that they are unclear, and one must interpret the argument according to what the author intended to say. If we apply the steps from the previous examples, first label the premises and conclusion with letters:

(C) I think that Lucy is mortal. (P) She is human, and (P) humans are mortal.

Now that the argument is labeled, order the argument vertically with abbreviations in parentheses, and then **observe** the added keywords that provide a clear interpretation. For example:

1. **Lucy** is human. (P)
2. **All** humans are mortal. (P)
3. **Therefore**, Lucy is mortal. (C)

Now the final version of that argument is clearer. We ordered the premises and conclusion vertically, replaced the pronoun “she” with “Lucy,” added the keyword “All” to premise (2), on the assumption that the author intended to refer to “all” humans and not “some” humans, and added the conclusion keyword “Therefore.”

The second more complex example is the following:
> “Dogs must be man’s best friend.” Dogs are loyal and kind.”

In this example, there are no relevant keywords, and the conclusion may not be obvious. The task, then, is to carefully interpret the sentences and their relationship with each other to discover (1) does an argument even exist? and (2), if yes, then what are the premises and the conclusion?

Identifying the argument can be difficult. One technique for identifying obscure arguments like the one above is using the “Why/Because” strategy. A conclusion can always be followed by asking a hypothetical “Why?” and a premise can always be introduced with the term “Because.” Consider the following:  

> “Dogs must be man’s best friend. (**Why**)?...(**Because**) Dogs are loyal and (**Because**) dogs are kind.”

The first statement, “Dogs must be man’s best friend,” can be followed by asking “**Why** do you think that claim is true?” The second and third statements can be introduced with the term “because”. This process demonstrates that the first statement, followed by the term “why,” is the conclusion, and the second and third statements, preceded with the term “because,” are the premises. So, in difficult cases with a lack of keywords, locate the statements and note which statement best follows with a “Why?” (likely the conclusion), and the statements that best precede with a “Because” (likely the premises supporting that conclusion).

However, at times that strategy may create confusion because most statements could in principle be followed with a hypothetical “Why?” For example:

> “Dogs must be man’s best friend. Dogs are loyal **(Why?)** and dogs are kind.”

In that example, the statement followed by the hypothetical “why?” is not the conclusion, but one could technically apply the strategy in that case, thereby creating confusion. How does one resolve this confusion? One strategy is to answer the “Why” question with the other statements involved, and test and compare each statement with another until the conclusion becomes more apparent. For example, suppose one wishes to test the statement, “Dogs are loyal,” to discover if that statement is the conclusion:

> “Dogs are loyal.” **Why?**

Answer that question by using only the other two statements involved, for example:

1. Dogs are loyal. **Why? Because** dogs must be man’s best friend.
2. Dogs are loyal. **Why? Because** dogs are kind.

Neither answer to the question seems accurate, because dog loyalty has to do with other characteristics absent from those statements. That process indicates that the statement, “dogs are loyal,” is likely not the conclusion. Repeat the process with the other two statements until a conclusion becomes evident.  If there’s no apparent conclusion, then that may show the argument is poorly constructed.

A final comment is the terms “why” and “because” may be used in sentences without invoking an argument. For example,

> “I’m at the birthday party because I was invited.”

Those statements do not (really) constitute an argument even though the term “because” is used and the term “why” is implied.

### Label and Structure the Arguments Vertically {-}

**This activity has two steps. The first step is to click/drag the appropriate letter into the box to label the premises and conclusion. In the second step, click/drag the appropriate premise and conclusion to complete the vertical argument.**

**Checklist**

- Focus on statements and ignore non-statements.
- Locate the premises and conclusion using keywords. **NOTE: use the “Why/Because” strategy for difficult cases.**
- Label the premises and conclusion using letters in parentheses.
- Restructure the argument vertically, with premises on top and the conclusion on the bottom.
- **Note the keywords that are added to the premises and conclusions in step 2.**

Example:

> “I think all children are artists. Marcie is a child. Marcie must be an artist.”

**Step 1:** Label the arguments

> (P) I think all children are artists. (P) Marcie is a child. (C) Marcie must be an artist.

**Step 2:** Restructure the argument vertically

1. **All** children are artists. (P)
2. Marcie is a child. (P)
3. **Therefore**, Marcie is an artist. (C)

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=425" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Logic Exercise 2 {-}

```{block2, type='reflect'}

Some arguments use sentences with the terms “If…Then.” These types of sentences are called conditional sentences (or conditionals) and often appear in arguments. For example:

> “**IF** Willy is a whale, **THEN** Willy is a mammal.”

As discussed briefly in an earlier section, note that some sentences may include multiple statements and thus include multiple premises. However, note that conditional sentences, while they may include multiple statements, **always constitute one premise**. That is, both “If…Then” statements in a conditional sentence are not different premises of the argument but are parts of the same premise.

For example:
1. **If Willy is a whale, then Willy is a mammal.** (P)
2. Willy is a whale. (P2)
3. Therefore, Willy is a mammal. (C1)

**The first premise includes both “If…Then” statements**, and both statements in the conditional can be defined. The first statement following the term “If” is called the **antecedent**. That means the thing that comes before. The second statement following the term “Then” is called the **consequent**. That means the thing that comes after, or the thing that follows from the antecedent, for example:

> “If Willy is a whale (antecedent), then Willy is a mammal (consequent).”

Conditional sentences are tricky business. While we needn’t be concerned with those difficulties in this Unit, three factors deserve attention for the purpose of identifying arguments: (i) notice that the terms “if'' and “then” are keywords that may indicate a conditional premise; (ii), notice the conclusion in the argument above, “Willy is a mammal,” is smuggled into the second part (the consequent) of the first premise. When identifying a conditional sentence, the consequent of that conditional may be a clue for locating the conclusion (not always, but sometimes); and (iii), conditional sentences can be expressed in English in different ways. So one must learn to identify some of these expressions and practice how to convert them into standard “If…then” form.

**a. Sentences with the term “if” in the middle**

> “Willy is a mammal **IF** Willy is a whale.”

**The term “if” introduces the antecedent, and the antecedent always comes first in the conditional sentence**. So, rewrite the sentence above to standard conditional form by moving the term “if” and the antecedent, “Willy is a whale,” to the beginning of the sentence, and add the term “then” to the beginning of the consequent, “Willy is a mammal”:

> “**If** Willy is a whale, **then** Willy is a mammal.”

Now the argument can be structured vertically, for example:
1. If Willy is a whale, then Willy is a mammal. (P)
2. Willy is a whale. (P)
3. Therefore, Willy is a mammal. (C)

**b. Sentences with the phrase “only if” at the beginning**
> “**Only if** Willy is a mammal, is Willy a whale.”

**The term “only if” introduces the consequent, and the consequent is always located at the end of the conditional sentence**. So, change the term “only if” to “then” and move its consequent, “Willy is a mammal,” to the end. Then move the last statement, “Willy is a whale,” to the beginning with the term “If” added in front because that statement is the antecedent.

> “If Willy is a whale, then Willy is a mammal.”

**c.  Sentences with the phrase “only if” in the middle:**
> “Willy is a whale only if Willy is a mammal.”

Note, again, that the phrase “**only if**” introduces the consequent. Rewrite the sentence by converting “only if” to “then,” and add the term “If” to the beginning.

> “If Willy is a whale, then Willy is a mammal.”

**d. Sentences with the term “unless” at the beginning**
> “**Unless** you eat vegetables, there’s no dessert.”

**The term “unless” introduces the antecedent with a negation** (i.e. “not”) and is translated to “**if not.**” So, rewrite by replacing “unless” with “if not” and add the term “then” to the beginning of the consequent.

“**If not** you eat vegetables, **then** there’s no dessert.”

Obviously, that sentence above, although logically correct, must be rewritten to make sense:
> “**If** you do **not** eat vegetables, then there’s no dessert.”

**e. Sentences with the term “unless” in the middle**
> “There’s no dessert UNLESS you eat vegetables.”

Rewrite by changing “unless” to “if not,” move “if not” and its statement, “you eat vegetables,” to the beginning to make the antecedent; add “then” to the second statement, “there’s no dessert,” to make the consequent.

> “**If** you do not eat vegetables, **then** there’s no dessert.”

**f. Sentences with the phrase “provided that”**
> “You may eat dessert **provided that** you eat vegetables.”

**The phrase “provided that” introduces the antecedent**. Rewrite by changing “provided that” to “if” and move “if” and its statement, “you eat vegetables,” to the beginning to make the antecedent; add the term “then” to the beginning of the other statement, “You may eat dessert,” to make the consequent, for example:

> “**If** you eat vegetables, **then** you may eat dessert.”

Now you know how to identify different ways of expressing “If…then,” and how to rewrite those expressions to simplify ordering the argument vertically.

**Conditional Sentences Cheat Sheet**

1. Antecedent: the first statement in a conditional sentence introduced with the term “If”
2. Consequent: the second statement in a conditional sentence introduced with the term “then”
3. “If” = always introduces the antecedent, regardless of location
4. “Only if” = always introduces the consequent, regardless of location
5. “Unless” = always introduces the antecedent with a negation, regardless of location, translated as “if not”
6. “Provided that” = always introduces the antecedent regardless of location

### Arguments with Conditionals {-}

**This activity has two steps. The first step is to click/drag the appropriate letter into the box to label the premises and conclusion. In the second step, click/drag the appropriate premise and conclusion to complete the vertical argument.**

**Checklist**

- Focus on statements and ignore non-statements.
- Locate the premises and conclusion using keywords. **NOTE: the terms “if” and “then” may be keywords for indicating a conditional sentence and a premise of an argument. NOTE: expressions such as “only if” and “unless” (in green) indicate conditionals. Note how those expressions (in green) will change to standard “If/Then” conditionals when ordering the argument vertically.**
- Label the premises and conclusion using letters in parentheses.
- Restructure the argument vertically, with premises on top and the conclusion beneath.
- **Notice the changes to the wording in some of the premises and conclusions.**

Example 1:
> “If that thing walks like a duck, then that thing is a duck. That thing walks like a duck. Therefore, that thing is a duck.

**Step 1:** Label the argument

> (P) If that thing walks like a duck, then that thing is a duck. (P) That thing walks like a duck. (C) Therefore, that thing is a duck.

**Step 2:** Restructure the argument vertically
1. If that animal walks like a duck, then that animal is a duck.
2. That animal walks like a duck.
3. Therefore, that animal is a duck.

Example 2:
> “I’ll marry you only if you watch Downton Abbey. What!? You refuse to watch Downton Abbey. You’re kidding me! Well, I refuse to marry you.”

**Step 1:** Label the argument (notice the change from "only if" to "if then")

> (P) If I marry you, then you must watch Downton Abbey. (P) You refuse to watch Downton Abbey. (C) I will not marry you.

**Step 2:** Restructure the argument vertically
1. If I marry you, then you must watch Downton Abbey
2. You refuse to watch Downton Abbey
3. Thus, I will not marry you.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=426" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 6 minute optional video, you will be introduced to some further techniques for identifying arguments.

[Watch: *Lesson 2. Identifying Arguments*](https://www.youtube.com/watch?v=lYiEj5z8le8){target="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/lYiEj5z8le8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

## 3.4 Identifying and Practicing Difficult Arguments {-}

Follow and complete the steps below to accomplish your learning for this topic.

1. Read Topic Notes
2. Watch Topic Video
3. Complete Logic Exercise
4. Complete Practice Exercises
5. Watch Optional Video

### Topic Notes {-}

In the previous topics, we have attempted to build our foundation for identifying arguments. The real challenge is when we’re confronted with long speeches, texts, reports, stories, and accusations whereby the argument may often seem unclear. Our task is to use the tools we’ve learned to identify the argument(s) in more difficult contexts. In this topic, we practice these skills by following these steps: (i) ignore non-statements and label the premises and conclusion; (ii) restructure the argument vertically with premises on top and the conclusion beneath. Notice that the difficult step is (i). We must sift through the content to locate keywords, interpret ambiguous statements, possibly use the “Why/Because” strategy in cases of doubt, decipher unusual “if/then” statements, and so on. Sometimes there is no argument at all; other times there may exist more than one argument, such that there is a main argument, and a secondary argument. The point of this entire exercise is to learn the skill that so many of us fail to properly master: to learn what the opposing person is trying to say. What is their position? What is their argument if there is one? Only after we’ve successfully identified the argument can we then properly raise objections and evaluate their argument.

### Topic Video {-}

In this video, you will learn how to use the previous tools and strategies to identify difficult arguments. These arguments are often a challenge to locate because they exist within a longer text or speech. These texts and speeches often include irrelevant information and non-statements that make identification difficult.

**Identifying and Practicing Difficult Arguments Unit 3 Topic 4** Video (8 min 03 sec)

<div class="video-container">

<iframe src=https://player.vimeo.com/video/889165070?h=1f15d261ff&amp;badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479 width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" title="PHIL 100 - Unit 3, Topic 4, Difficult Arguments"></iframe>

</div>

### Logic Exercise {-}

```{block2, type='reflect'}

In the previous topics, we learned about identifying arguments. In this final topic, we apply those tools to identifying more difficult arguments. The examples below are more challenging because the arguments are not only greater length, but the arguments can be difficult to identify. One must carefully sift through the statements to decipher (i) does an argument exist, and (ii) if yes, then what is the conclusion(s) and the premises supporting that conclusion(s)? One must employ all the methods to achieve those tasks: such as ignoring non-statements, search for keywords that indicate premises and conclusions (highlight them, if that helps), label the premises and conclusions in parentheses, interpret what the author intended to say, and restructure the argument vertically in its strongest form. Note: more complex arguments often include multiple conclusions and those conclusions may operate as premises of the same argument. Note: when encountering a lengthy passage, read the entire passage through multiple times before attempting to identify the parts of the argument. The reason for that is to gain a broader understanding of what the author intended to say.  

**Checklist**

- Focus on statements and ignore non-statements
- Locate the premises and conclusion using keywords
- Label the premises and conclusion using letters and numerals in parentheses
- Restructure the argument vertically, with premises on top and the conclusion beneath

Example 3 is more challenging. In these types of cases, read through the entire passage several times to decipher the argument exactly. Take time to draft multiple arguments vertically and observe which version best represents what the author intended to say.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=432" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=433" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=434" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Practice Exercises {-}

```{block2, type='reflect'}

These practice exercises are optional and not graded. However, the more you practice and become familiar with identifying arguments, the more prepared you will be for your Final Course Reflection Assignment.

If you want to keep your answers for future reference, click the Download button on the left after you’ve completed the exercise and save the answers to your computer.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=589" width="936" height="1782" frameborder="0" allowfullscreen="allowfullscreen" title="PHIL 100 Unit 1"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

### Optional Video {-}

```{block2, type='reflect'}

In this 5 minute 34 second optional video, you will be introduced to strategies for locating terms that describe parts of the argument in difficult passages, such as terms that pick out conclusions and premises.

[Watch: *Identifying Premises and Conclusions*](https://www.youtube.com/watch?v=07mehbgE5jc){target="_blank"}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/07mehbgE5jc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```